CREATE TABLE users
(
    id            INT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    email_address VARCHAR(128)             NOT NULL,
    name          VARCHAR(128)             NOT NULL,
    password_salt VARCHAR(128)             NULL,
    password_hash VARCHAR(128)             NULL,
    is_deleted    BOOL,
    PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    name                VARCHAR(128)             NOT NULL,
    short_name          VARCHAR(128)             NOT NULL,
    type                VARCHAR(32)              NOT NULL,
    diversity_score     SMALLINT                 NOT NULL,
    union_score         SMALLINT                 NOT NULL,
    environmental_score SMALLINT                 NOT NULL,
    lobbying_score      SMALLINT                 NOT NULL,
    linked_subject_id   INT                      NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_subjects_linked_subject_id ON subjects (linked_subject_id);

CREATE INDEX idx_subjects_short_name ON subjects (short_name);

CREATE INDEX idx_subjects_type ON subjects (type) INCLUDE (name);

CREATE TABLE scores
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    source_url         VARCHAR                  NOT NULL,
    headline           VARCHAR                  NOT NULL,
    number             SMALLINT                 NOT NULL,
    topic              VARCHAR(32)              NOT NULL,
    is_approved        BOOL,
    created_by_user_id INT                      NOT NULL,
    subject_id         INT                      NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_scores_subject_id ON scores (subject_id) INCLUDE (topic, is_approved, created_by_user_id);
